# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{shawty-server}
  s.version = "1.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jack Danger Canty"]
  s.date = %q{2011-05-04}
  s.description = %q{Run your own url shortener add your own web address for free on Heroku.com}
  s.email = %q{gitcommit@6brand.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown"
  ]
  s.files = [
    ".gems",
    "LICENSE",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "config.ru",
    "config/database.yml",
    "shawty-server.gemspec",
    "shawty.rb",
    "test.rb"
  ]
  s.homepage = %q{http://github.com/JackDanger/shawty-server}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.2}
  s.summary = %q{Ultra-lightweight url shortening server for Heroku.com}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rack>, ["= 1.2.1"])
      s.add_runtime_dependency(%q<alphadecimal>, [">= 1.0.1"])
      s.add_development_dependency(%q<active_record>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
    else
      s.add_dependency(%q<rack>, ["= 1.2.1"])
      s.add_dependency(%q<alphadecimal>, [">= 1.0.1"])
      s.add_dependency(%q<active_record>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<rack>, ["= 1.2.1"])
    s.add_dependency(%q<alphadecimal>, [">= 1.0.1"])
    s.add_dependency(%q<active_record>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
  end
end

